### ISSUE TITLE
Build Macos Error

### ISSUE THREAD

**Issue by yusifahmadov** [leanflutter/auto_updater#14]
```
Unhandled exception:
ProcessException: No such file or directory
  Command: /Users/yusifahmadov/Desktop/crmappnew/macos/Pods/Sparkle/bin/generate_keys 
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      main (file:///Users/yusifahmadov/development/flutter/.pub-cache/hosted/pub.dartlang.org/auto_updater-0.1.4/bin/generate_keys.dart:19:35)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)



```

i got a error when i run flutter pub run auto_updater:generate_keys

**Comment by thanhhuy0611** [comment]
I meet the same error. How can you fix it? @yusifahmadov

**Comment by yusifahmadov** [comment]
> I meet the same error. How can you fix it? @yusifahmadov 

İ dont remember (

**Comment by thanhhuy0611** [comment]
> > I meet the same error. How can you fix it? @yusifahmadov
> 
> İ dont remember (

I just fix it by run pod install to get package Sparkle
