### ISSUE TITLE
 dart run auto_updater:generate_keys  error

### ISSUE THREAD

**Issue by cpsoft** [leanflutter/auto_updater#52]
Building package executable...
Built auto_updater:generate_keys.
Unhandled exception:
FormatException: Unexpected extension byte (at offset 10)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1851:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2381:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#16     _StreamController._add (dart:async/stream_controller.dart:650:7)
#17     _StreamController.add (dart:async/stream_controller.dart:598:5)

**Comment by lingsifeng** [comment]
我也遇到了这个问题，请问你解决没有

**Comment by lingsifeng** [comment]
I also ran into this issue, how did you solve it？

**Comment by yuhaya** [comment]
same

**Comment by yuhaya** [comment]
It may be a network problem. After adjusting the network here, it is normal.

**Comment by Eric0x** [comment]
[auto_updater](https://github.com/leanflutter/auto_updater/tree/8e367a5e2d83f2cb1884a5bcacb6148de791114e)/[bin](https://github.com/leanflutter/auto_updater/tree/8e367a5e2d83f2cb1884a5bcacb6148de791114e/bin)
/generate_keys.dart
Finally, this was executed  windows/WinSparkle-0.8.0/bin/generate_keys.bat

**Comment by ismanong** [comment]
中文环境下的dart的Process进程需要`chcp 65001`

**Comment by a1239897580** [comment]
同样的问题  怎么解决

**Comment by LIAO-JIA-LE** [comment]
I tried using this method to resolve the issue and successfully fixed it. I hope it helps you.

The issue might be caused by using OpenSSL. First, you need to install OpenSSL (I didn’t use Chocolatey; instead, I downloaded Win64 OpenSSL v3.3.2 EXE from this [link](https://slproweb.com/products/Win32OpenSSL.html)).

Next, you need to set the OpenSSL executable in the environment variables, making sure that when you run `dart run auto_updater:generate_keys`, it can utilize OpenSSL to generate keys. (I added `C:\Program Files\OpenSSL-Win64\bin` to the system environment variable `PATH`, as `openssl.exe` is located in this directory.)

After that, running `dart run auto_updater:generate_keys` should work!

I hope this helps you resolve the issue!
